version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo
    steps:
      # step 1: Obtain repo from github
      - checkout
      # step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      # step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
